[[constraint]]
  name = "github.com/labstack/echo"
  version = "2.0.2"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "1.10.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/topfreegames/extensions"
  version = "8.0.1"

[[constraint]]
  name = "github.com/mailru/easyjson"
  branch = "master"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "~6.12.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.3.1"

[prune]
  go-tests = true
  unused-packages = true
